// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 17.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace T4vsRazor
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class SearchEmployee : TemplateBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("﻿");
            this.Write("select\r\n\t*\r\nfrom\r\n\tEmployy\r\nwhere\r\n\t1 = 1\r\n");
 if (FirstName is not null) { 
            this.Write("\tand FirstName = @FirstName\r\n");
 } 
 if (LastName is not null) { 
            this.Write("\tand LastName = @LastName\r\n");
 } 
            return this.GenerationEnvironment.ToString();
        }
    }
}
