name: ➕ Copilotへ新しいモデルの追加
title: "Copilotへ新しいモデル <model_name in Copilot> の追加リクエスト"
description: Copilotへ新しいモデルを追加するリクエスト
labels: ["enhancement"]
assignees: []
projects: []
body:
  - type: markdown
    attributes:
      value: |
        以下のチェック項目を確認のうえ、モデル名をタイトルに入力してください。
        
        **モデル名の形式**: `<ベンダー名> <モデル名> in Copilot`
        
        例: `OpenAI GPT-6 in Copilot` または `Anthropic Claude Sonnet 5 in Copilot`
        
        ※ `(Preview)` が含まれている場合は自動的に削除されます。

  - type: checkboxes
    attributes:
      label: 確認事項
      options:
        - label: 対象のモデルが現在Disableで有効化できないことを確認しました

  - type: markdown
    attributes:
      value: |
        ---
        
        ### 実行手順
        
        1. **Issueからモデル名を抽出**
           - Issueのタイトルから新しいモデル名を取得します
           - タイトル形式: "Copilotへ新しいモデル <model_name in Copilot> の追加リクエスト"
           - モデル名は既に " in Copilot" を含んでいます（例: "OpenAI GPT-6 in Copilot"）
           - モデル名に "(Preview)" が含まれている場合は削除します
        
        2. **モデル情報の準備**
           - 抽出したモデル名から "(Preview)" を削除した形式を使用します
           - デフォルトの設定値: "Let Organizations decide"
        
        3. **AI Controls.mdの更新**
           - ファイルパス: `enterprise-settings/AI Controls.md`
           - 対象セクション: "Configure allowed models" → "現状の設定" のテーブル（31-47行目付近）
           - 新しいモデルを以下のルールに従って挿入:
             - ベンダー順（Anthropic → Google → OpenAI → xAI）
             - 各ベンダー内ではモデル名のアルファベット順
           
           テーブル形式:
           ```markdown
           | <Model Name> in Copilot | Let Organizations decide |
           ```
        
        4. **Pull Requestの作成**
           - ブランチ名: `add-model/<model-name-slug>` （例: `add-model/openai-gpt-6`）
           - PRテンプレート: `.github/PULL_REQUEST_TEMPLATE/add-model-to-copilot.md` を使用
           - PRタイトル: Issueタイトルと完全に一致させる（例: "Copilotへ新しいモデル OpenAI GPT-6 in Copilot の追加リクエスト"）
           - PR本文で以下を記入:
             - モデル名
             - 設定値（デフォルト: "Let Organizations decide"）
             - 変更ファイルのチェック
             - 関連Issue番号
        
        5. **バリデーション**
           - モデル名が正確に記載されているか確認
           - テーブルのMarkdown形式が正しいか確認
           - アルファベット順・製品順に適切な位置に挿入されているか確認
        
        ### エラーハンドリング
        
        - Issueタイトルからモデル名を抽出できない場合は、ユーザーに確認を求める
        - 既に同じモデルがテーブルに存在する場合は、重複追加を防ぐ
        - テーブルの形式が壊れないよう、慎重に編集する
        
        ### 出力例
        
        Issueタイトル: "Copilotへ新しいモデル OpenAI GPT-6 in Copilot の追加リクエスト"
        
        更新内容:
        ```markdown
        | OpenAI GPT-6 in Copilot | Let Organizations decide |
        ```
        
        挿入位置: OpenAI GPT-5.1シリーズの後、xAI Grok Code Fast 1の前