name: ➕ Copilotへ新しいモデルの追加
title: "Copilotへ新しいモデル <COPILOT_MODEL_NAME> の追加リクエスト"
description: Copilotへ新しいモデルを追加するリクエスト
labels: ["enhancement"]
assignees: ["nuitsjp"]
projects: []
body:
  - type: markdown
    attributes:
      value: |
        追加希望のモデル名をタイトルの<COPILOT_MODEL_NAME>に入力してください。
        
        例: 
        - 追加対象のモデル名: `OpenAI GPT-5.2 in Copilot`
        - タイトル         :  `Copilotへ新しいモデル OpenAI GPT-5.2 in Copilot の追加リクエスト`

  - type: checkboxes
    attributes:
      label: 確認事項
      options:
        - label: 対象のモデルが現在Disableで有効化できないことを確認しました
          required: true