// This is the output code from your template
// you only get syntax-highlighting here - not intellisense
namespace EventInfoAnalizerConsole {
	class EventWriter {
		public static void WriteInfo (){
			System.Console.WriteLine("Application");
			System.Console.WriteLine("Application");
			System.Console.WriteLine("Application");
			System.Console.WriteLine("Application");
			System.Console.WriteLine("Button");
			System.Console.WriteLine("Button");
			System.Console.WriteLine("Button");
			System.Console.WriteLine("Cell");
			System.Console.WriteLine("Cell");
			System.Console.WriteLine("Cell");
			System.Console.WriteLine("Cell");
			System.Console.WriteLine("ClickGestureRecognizer");
			System.Console.WriteLine("ColumnDefinition");
			System.Console.WriteLine("DatePicker");
			System.Console.WriteLine("Editor");
			System.Console.WriteLine("Editor");
			System.Console.WriteLine("Element");
			System.Console.WriteLine("Element");
			System.Console.WriteLine("Element");
			System.Console.WriteLine("Element");
			System.Console.WriteLine("Element");
			System.Console.WriteLine("Entry");
			System.Console.WriteLine("Entry");
			System.Console.WriteLine("EntryCell");
			System.Console.WriteLine("Layout");
			System.Console.WriteLine("ListView");
			System.Console.WriteLine("ListView");
			System.Console.WriteLine("ListView");
			System.Console.WriteLine("ListView");
			System.Console.WriteLine("ListView");
			System.Console.WriteLine("ListView");
			System.Console.WriteLine("MasterDetailPage");
			System.Console.WriteLine("MasterDetailPage");
			System.Console.WriteLine("MenuItem");
			System.Console.WriteLine("NavigationPage");
			System.Console.WriteLine("NavigationPage");
			System.Console.WriteLine("NavigationPage");
			System.Console.WriteLine("NavigationPage");
			System.Console.WriteLine("NavigationPage");
			System.Console.WriteLine("NavigationPage");
			System.Console.WriteLine("NavigationPage");
			System.Console.WriteLine("NavigationPage");
			System.Console.WriteLine("OpenGLView");
			System.Console.WriteLine("Page");
			System.Console.WriteLine("Page");
			System.Console.WriteLine("Page");
			System.Console.WriteLine("PanGestureRecognizer");
			System.Console.WriteLine("Picker");
			System.Console.WriteLine("PinchGestureRecognizer");
			System.Console.WriteLine("RowDefinition");
			System.Console.WriteLine("ScrollView");
			System.Console.WriteLine("ScrollView");
			System.Console.WriteLine("SearchBar");
			System.Console.WriteLine("SearchBar");
			System.Console.WriteLine("Slider");
			System.Console.WriteLine("Stepper");
			System.Console.WriteLine("Switch");
			System.Console.WriteLine("SwitchCell");
			System.Console.WriteLine("TableView");
			System.Console.WriteLine("TapGestureRecognizer");
			System.Console.WriteLine("ToolbarItem");
			System.Console.WriteLine("VisualElement");
			System.Console.WriteLine("VisualElement");
			System.Console.WriteLine("VisualElement");
			System.Console.WriteLine("VisualElement");
			System.Console.WriteLine("VisualElement");
			System.Console.WriteLine("VisualElement");
			System.Console.WriteLine("VisualElement");
			System.Console.WriteLine("WebView");
			System.Console.WriteLine("WebView");
			System.Console.WriteLine("WebView");
			System.Console.WriteLine("WebView");
			System.Console.WriteLine("WebView");
		}
    }
}
