
// This file was automatically generated by the Dapper.FastCRUD T4 Template
// Do not make changes directly to this file - edit the template configuration instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `AdventureWorks2017`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=localhost\SQLEXPRESS;Initial Catalog=AdventureWorks2017;Integrated Security=True;`
//     Include Views:          `True`

namespace Dapper.FastCrud.Tests.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the EmployeePayHistory table.
    /// </summary>
	[Table("EmployeePayHistory")]
	public partial class EmployeePayHistory
	{
		[Key]
	    public virtual int BusinessEntityID { get; set; }
		[Key]
	    public virtual DateTime RateChangeDate { get; set; }
	    public virtual decimal Rate { get; set; }
	    public virtual byte PayFrequency { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the SalesOrderHeaderSalesReason table.
    /// </summary>
	[Table("SalesOrderHeaderSalesReason")]
	public partial class SalesOrderHeaderSalesReason
	{
		[Key]
	    public virtual int SalesOrderID { get; set; }
		[Key]
	    public virtual int SalesReasonID { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the SalesPerson table.
    /// </summary>
	[Table("SalesPerson")]
	public partial class SalesPerson
	{
		[Key]
	    public virtual int BusinessEntityID { get; set; }
	    public virtual int? TerritoryID { get; set; }
	    public virtual decimal? SalesQuota { get; set; }
	    public virtual decimal Bonus { get; set; }
	    public virtual decimal CommissionPct { get; set; }
	    public virtual decimal SalesYTD { get; set; }
	    public virtual decimal SalesLastYear { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Illustration table.
    /// </summary>
	[Table("Illustration")]
	public partial class Illustration
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int IllustrationID { get; set; }
	    public virtual string Diagram { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the JobCandidate table.
    /// </summary>
	[Table("JobCandidate")]
	public partial class JobCandidate
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int JobCandidateID { get; set; }
	    public virtual int? BusinessEntityID { get; set; }
	    public virtual string Resume { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Location table.
    /// </summary>
	[Table("Location")]
	public partial class Location
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual short LocationID { get; set; }
	    public virtual string Name { get; set; }
	    public virtual decimal CostRate { get; set; }
	    public virtual decimal Availability { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Password table.
    /// </summary>
	[Table("Password")]
	public partial class Password
	{
		[Key]
	    public virtual int BusinessEntityID { get; set; }
	    public virtual string PasswordHash { get; set; }
	    public virtual string PasswordSalt { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the SalesPersonQuotaHistory table.
    /// </summary>
	[Table("SalesPersonQuotaHistory")]
	public partial class SalesPersonQuotaHistory
	{
		[Key]
	    public virtual int BusinessEntityID { get; set; }
		[Key]
	    public virtual DateTime QuotaDate { get; set; }
	    public virtual decimal SalesQuota { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Person table.
    /// </summary>
	[Table("Person")]
	public partial class Person
	{
		[Key]
	    public virtual int BusinessEntityID { get; set; }
	    public virtual string PersonType { get; set; }
	    public virtual bool NameStyle { get; set; }
	    public virtual string Title { get; set; }
	    public virtual string FirstName { get; set; }
	    public virtual string MiddleName { get; set; }
	    public virtual string LastName { get; set; }
	    public virtual string Suffix { get; set; }
	    public virtual int EmailPromotion { get; set; }
	    public virtual string AdditionalContactInfo { get; set; }
	    public virtual string Demographics { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the SalesReason table.
    /// </summary>
	[Table("SalesReason")]
	public partial class SalesReason
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int SalesReasonID { get; set; }
	    public virtual string Name { get; set; }
	    public virtual string ReasonType { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the SalesTaxRate table.
    /// </summary>
	[Table("SalesTaxRate")]
	public partial class SalesTaxRate
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int SalesTaxRateID { get; set; }
	    public virtual int StateProvinceID { get; set; }
	    public virtual byte TaxType { get; set; }
	    public virtual decimal TaxRate { get; set; }
	    public virtual string Name { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the PersonCreditCard table.
    /// </summary>
	[Table("PersonCreditCard")]
	public partial class PersonCreditCard
	{
		[Key]
	    public virtual int BusinessEntityID { get; set; }
		[Key]
	    public virtual int CreditCardID { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the vAdditionalContactInfo view.
    /// </summary>
	[Table("vAdditionalContactInfo")]
	public partial class vAdditionalContactInfo
	{
	    public virtual int BusinessEntityID { get; set; }
	    public virtual string FirstName { get; set; }
	    public virtual string MiddleName { get; set; }
	    public virtual string LastName { get; set; }
	    public virtual string TelephoneNumber { get; set; }
	    public virtual string TelephoneSpecialInstructions { get; set; }
	    public virtual string Street { get; set; }
	    public virtual string City { get; set; }
	    public virtual string StateProvince { get; set; }
	    public virtual string PostalCode { get; set; }
	    public virtual string CountryRegion { get; set; }
	    public virtual string HomeAddressSpecialInstructions { get; set; }
	    public virtual string EMailAddress { get; set; }
	    public virtual string EMailSpecialInstructions { get; set; }
	    public virtual string EMailTelephoneNumber { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the PersonPhone table.
    /// </summary>
	[Table("PersonPhone")]
	public partial class PersonPhone
	{
		[Key]
	    public virtual int BusinessEntityID { get; set; }
		[Key]
	    public virtual string PhoneNumber { get; set; }
		[Key]
	    public virtual int PhoneNumberTypeID { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the vEmployee view.
    /// </summary>
	[Table("vEmployee")]
	public partial class vEmployee
	{
	    public virtual int BusinessEntityID { get; set; }
	    public virtual string Title { get; set; }
	    public virtual string FirstName { get; set; }
	    public virtual string MiddleName { get; set; }
	    public virtual string LastName { get; set; }
	    public virtual string Suffix { get; set; }
	    public virtual string JobTitle { get; set; }
	    public virtual string PhoneNumber { get; set; }
	    public virtual string PhoneNumberType { get; set; }
	    public virtual string EmailAddress { get; set; }
	    public virtual int EmailPromotion { get; set; }
	    public virtual string AddressLine1 { get; set; }
	    public virtual string AddressLine2 { get; set; }
	    public virtual string City { get; set; }
	    public virtual string StateProvinceName { get; set; }
	    public virtual string PostalCode { get; set; }
	    public virtual string CountryRegionName { get; set; }
	    public virtual string AdditionalContactInfo { get; set; }
	}

    /// <summary>
    /// A class which represents the SalesTerritory table.
    /// </summary>
	[Table("SalesTerritory")]
	public partial class SalesTerritory
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int TerritoryID { get; set; }
	    public virtual string Name { get; set; }
	    public virtual string CountryRegionCode { get; set; }
	    public virtual string Group { get; set; }
	    public virtual decimal SalesYTD { get; set; }
	    public virtual decimal SalesLastYear { get; set; }
	    public virtual decimal CostYTD { get; set; }
	    public virtual decimal CostLastYear { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the vEmployeeDepartment view.
    /// </summary>
	[Table("vEmployeeDepartment")]
	public partial class vEmployeeDepartment
	{
	    public virtual int BusinessEntityID { get; set; }
	    public virtual string Title { get; set; }
	    public virtual string FirstName { get; set; }
	    public virtual string MiddleName { get; set; }
	    public virtual string LastName { get; set; }
	    public virtual string Suffix { get; set; }
	    public virtual string JobTitle { get; set; }
	    public virtual string Department { get; set; }
	    public virtual string GroupName { get; set; }
	    public virtual DateTime StartDate { get; set; }
	}

    /// <summary>
    /// A class which represents the PhoneNumberType table.
    /// </summary>
	[Table("PhoneNumberType")]
	public partial class PhoneNumberType
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int PhoneNumberTypeID { get; set; }
	    public virtual string Name { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the vEmployeeDepartmentHistory view.
    /// </summary>
	[Table("vEmployeeDepartmentHistory")]
	public partial class vEmployeeDepartmentHistory
	{
	    public virtual int BusinessEntityID { get; set; }
	    public virtual string Title { get; set; }
	    public virtual string FirstName { get; set; }
	    public virtual string MiddleName { get; set; }
	    public virtual string LastName { get; set; }
	    public virtual string Suffix { get; set; }
	    public virtual string Shift { get; set; }
	    public virtual string Department { get; set; }
	    public virtual string GroupName { get; set; }
	    public virtual DateTime StartDate { get; set; }
	    public virtual DateTime? EndDate { get; set; }
	}

    /// <summary>
    /// A class which represents the vIndividualCustomer view.
    /// </summary>
	[Table("vIndividualCustomer")]
	public partial class vIndividualCustomer
	{
	    public virtual int BusinessEntityID { get; set; }
	    public virtual string Title { get; set; }
	    public virtual string FirstName { get; set; }
	    public virtual string MiddleName { get; set; }
	    public virtual string LastName { get; set; }
	    public virtual string Suffix { get; set; }
	    public virtual string PhoneNumber { get; set; }
	    public virtual string PhoneNumberType { get; set; }
	    public virtual string EmailAddress { get; set; }
	    public virtual int EmailPromotion { get; set; }
	    public virtual string AddressType { get; set; }
	    public virtual string AddressLine1 { get; set; }
	    public virtual string AddressLine2 { get; set; }
	    public virtual string City { get; set; }
	    public virtual string StateProvinceName { get; set; }
	    public virtual string PostalCode { get; set; }
	    public virtual string CountryRegionName { get; set; }
	    public virtual string Demographics { get; set; }
	}

    /// <summary>
    /// A class which represents the Product table.
    /// </summary>
	[Table("Product")]
	public partial class Product
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int ProductID { get; set; }
	    public virtual string Name { get; set; }
	    public virtual string ProductNumber { get; set; }
	    public virtual bool MakeFlag { get; set; }
	    public virtual bool FinishedGoodsFlag { get; set; }
	    public virtual string Color { get; set; }
	    public virtual short SafetyStockLevel { get; set; }
	    public virtual short ReorderPoint { get; set; }
	    public virtual decimal StandardCost { get; set; }
	    public virtual decimal ListPrice { get; set; }
	    public virtual string Size { get; set; }
	    public virtual string SizeUnitMeasureCode { get; set; }
	    public virtual string WeightUnitMeasureCode { get; set; }
	    public virtual decimal? Weight { get; set; }
	    public virtual int DaysToManufacture { get; set; }
	    public virtual string ProductLine { get; set; }
	    public virtual string Class { get; set; }
	    public virtual string Style { get; set; }
	    public virtual int? ProductSubcategoryID { get; set; }
	    public virtual int? ProductModelID { get; set; }
	    public virtual DateTime SellStartDate { get; set; }
	    public virtual DateTime? SellEndDate { get; set; }
	    public virtual DateTime? DiscontinuedDate { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the vPersonDemographics view.
    /// </summary>
	[Table("vPersonDemographics")]
	public partial class vPersonDemographic
	{
	    public virtual int BusinessEntityID { get; set; }
	    public virtual decimal? TotalPurchaseYTD { get; set; }
	    public virtual DateTime? DateFirstPurchase { get; set; }
	    public virtual DateTime? BirthDate { get; set; }
	    public virtual string MaritalStatus { get; set; }
	    public virtual string YearlyIncome { get; set; }
	    public virtual string Gender { get; set; }
	    public virtual int? TotalChildren { get; set; }
	    public virtual int? NumberChildrenAtHome { get; set; }
	    public virtual string Education { get; set; }
	    public virtual string Occupation { get; set; }
	    public virtual bool? HomeOwnerFlag { get; set; }
	    public virtual int? NumberCarsOwned { get; set; }
	}

    /// <summary>
    /// A class which represents the vJobCandidate view.
    /// </summary>
	[Table("vJobCandidate")]
	public partial class vJobCandidate
	{
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int JobCandidateID { get; set; }
	    public virtual int? BusinessEntityID { get; set; }
	    public virtual string Name_Prefix { get; set; }
	    public virtual string Name_First { get; set; }
	    public virtual string Name_Middle { get; set; }
	    public virtual string Name_Last { get; set; }
	    public virtual string Name_Suffix { get; set; }
	    public virtual string Skills { get; set; }
	    public virtual string Addr_Type { get; set; }
	    public virtual string Addr_Loc_CountryRegion { get; set; }
	    public virtual string Addr_Loc_State { get; set; }
	    public virtual string Addr_Loc_City { get; set; }
	    public virtual string Addr_PostalCode { get; set; }
	    public virtual string EMail { get; set; }
	    public virtual string WebSite { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the vJobCandidateEmployment view.
    /// </summary>
	[Table("vJobCandidateEmployment")]
	public partial class vJobCandidateEmployment
	{
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int JobCandidateID { get; set; }
	    public virtual DateTime? Emp_StartDate { get; set; }
	    public virtual DateTime? Emp_EndDate { get; set; }
	    public virtual string Emp_OrgName { get; set; }
	    public virtual string Emp_JobTitle { get; set; }
	    public virtual string Emp_Responsibility { get; set; }
	    public virtual string Emp_FunctionCategory { get; set; }
	    public virtual string Emp_IndustryCategory { get; set; }
	    public virtual string Emp_Loc_CountryRegion { get; set; }
	    public virtual string Emp_Loc_State { get; set; }
	    public virtual string Emp_Loc_City { get; set; }
	}

    /// <summary>
    /// A class which represents the vJobCandidateEducation view.
    /// </summary>
	[Table("vJobCandidateEducation")]
	public partial class vJobCandidateEducation
	{
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int JobCandidateID { get; set; }
	    public virtual string Edu_Level { get; set; }
	    public virtual DateTime? Edu_StartDate { get; set; }
	    public virtual DateTime? Edu_EndDate { get; set; }
	    public virtual string Edu_Degree { get; set; }
	    public virtual string Edu_Major { get; set; }
	    public virtual string Edu_Minor { get; set; }
	    public virtual string Edu_GPA { get; set; }
	    public virtual string Edu_GPAScale { get; set; }
	    public virtual string Edu_School { get; set; }
	    public virtual string Edu_Loc_CountryRegion { get; set; }
	    public virtual string Edu_Loc_State { get; set; }
	    public virtual string Edu_Loc_City { get; set; }
	}

    /// <summary>
    /// A class which represents the vProductAndDescription view.
    /// </summary>
	[Table("vProductAndDescription")]
	public partial class vProductAndDescription
	{
		[Key]
	    public virtual int ProductID { get; set; }
	    public virtual string Name { get; set; }
	    public virtual string ProductModel { get; set; }
		[Key]
	    public virtual string CultureID { get; set; }
	    public virtual string Description { get; set; }
	}

    /// <summary>
    /// A class which represents the vProductModelCatalogDescription view.
    /// </summary>
	[Table("vProductModelCatalogDescription")]
	public partial class vProductModelCatalogDescription
	{
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int ProductModelID { get; set; }
	    public virtual string Name { get; set; }
	    public virtual string Summary { get; set; }
	    public virtual string Manufacturer { get; set; }
	    public virtual string Copyright { get; set; }
	    public virtual string ProductURL { get; set; }
	    public virtual string WarrantyPeriod { get; set; }
	    public virtual string WarrantyDescription { get; set; }
	    public virtual string NoOfYears { get; set; }
	    public virtual string MaintenanceDescription { get; set; }
	    public virtual string Wheel { get; set; }
	    public virtual string Saddle { get; set; }
	    public virtual string Pedal { get; set; }
	    public virtual string BikeFrame { get; set; }
	    public virtual string Crankset { get; set; }
	    public virtual string PictureAngle { get; set; }
	    public virtual string PictureSize { get; set; }
	    public virtual string ProductPhotoID { get; set; }
	    public virtual string Material { get; set; }
	    public virtual string Color { get; set; }
	    public virtual string ProductLine { get; set; }
	    public virtual string Style { get; set; }
	    public virtual string RiderExperience { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the vProductModelInstructions view.
    /// </summary>
	[Table("vProductModelInstructions")]
	public partial class vProductModelInstruction
	{
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int ProductModelID { get; set; }
	    public virtual string Name { get; set; }
	    public virtual string Instructions { get; set; }
	    public virtual int? LocationID { get; set; }
	    public virtual decimal? SetupHours { get; set; }
	    public virtual decimal? MachineHours { get; set; }
	    public virtual decimal? LaborHours { get; set; }
	    public virtual int? LotSize { get; set; }
	    public virtual string Step { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the vSalesPerson view.
    /// </summary>
	[Table("vSalesPerson")]
	public partial class vSalesPerson
	{
	    public virtual int BusinessEntityID { get; set; }
	    public virtual string Title { get; set; }
	    public virtual string FirstName { get; set; }
	    public virtual string MiddleName { get; set; }
	    public virtual string LastName { get; set; }
	    public virtual string Suffix { get; set; }
	    public virtual string JobTitle { get; set; }
	    public virtual string PhoneNumber { get; set; }
	    public virtual string PhoneNumberType { get; set; }
	    public virtual string EmailAddress { get; set; }
	    public virtual int EmailPromotion { get; set; }
	    public virtual string AddressLine1 { get; set; }
	    public virtual string AddressLine2 { get; set; }
	    public virtual string City { get; set; }
	    public virtual string StateProvinceName { get; set; }
	    public virtual string PostalCode { get; set; }
	    public virtual string CountryRegionName { get; set; }
	    public virtual string TerritoryName { get; set; }
	    public virtual string TerritoryGroup { get; set; }
	    public virtual decimal? SalesQuota { get; set; }
	    public virtual decimal SalesYTD { get; set; }
	    public virtual decimal SalesLastYear { get; set; }
	}

    /// <summary>
    /// A class which represents the SalesTerritoryHistory table.
    /// </summary>
	[Table("SalesTerritoryHistory")]
	public partial class SalesTerritoryHistory
	{
		[Key]
	    public virtual int BusinessEntityID { get; set; }
		[Key]
	    public virtual int TerritoryID { get; set; }
		[Key]
	    public virtual DateTime StartDate { get; set; }
	    public virtual DateTime? EndDate { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the vSalesPersonSalesByFiscalYears view.
    /// </summary>
	[Table("vSalesPersonSalesByFiscalYears")]
	public partial class vSalesPersonSalesByFiscalYear
	{
	    public virtual int? SalesPersonID { get; set; }
	    public virtual string FullName { get; set; }
	    public virtual string JobTitle { get; set; }
	    public virtual string SalesTerritory { get; set; }
	}

    /// <summary>
    /// A class which represents the vStateProvinceCountryRegion view.
    /// </summary>
	[Table("vStateProvinceCountryRegion")]
	public partial class vStateProvinceCountryRegion
	{
		[Key]
	    public virtual int StateProvinceID { get; set; }
	    public virtual string StateProvinceCode { get; set; }
	    public virtual bool IsOnlyStateProvinceFlag { get; set; }
	    public virtual string StateProvinceName { get; set; }
	    public virtual int TerritoryID { get; set; }
		[Key]
	    public virtual string CountryRegionCode { get; set; }
	    public virtual string CountryRegionName { get; set; }
	}

    /// <summary>
    /// A class which represents the vStoreWithDemographics view.
    /// </summary>
	[Table("vStoreWithDemographics")]
	public partial class vStoreWithDemographic
	{
	    public virtual int BusinessEntityID { get; set; }
	    public virtual string Name { get; set; }
	    public virtual decimal? AnnualSales { get; set; }
	    public virtual decimal? AnnualRevenue { get; set; }
	    public virtual string BankName { get; set; }
	    public virtual string BusinessType { get; set; }
	    public virtual int? YearOpened { get; set; }
	    public virtual string Specialty { get; set; }
	    public virtual int? SquareFeet { get; set; }
	    public virtual string Brands { get; set; }
	    public virtual string Internet { get; set; }
	    public virtual int? NumberEmployees { get; set; }
	}

    /// <summary>
    /// A class which represents the vStoreWithContacts view.
    /// </summary>
	[Table("vStoreWithContacts")]
	public partial class vStoreWithContact
	{
	    public virtual int BusinessEntityID { get; set; }
	    public virtual string Name { get; set; }
	    public virtual string ContactType { get; set; }
	    public virtual string Title { get; set; }
	    public virtual string FirstName { get; set; }
	    public virtual string MiddleName { get; set; }
	    public virtual string LastName { get; set; }
	    public virtual string Suffix { get; set; }
	    public virtual string PhoneNumber { get; set; }
	    public virtual string PhoneNumberType { get; set; }
	    public virtual string EmailAddress { get; set; }
	    public virtual int EmailPromotion { get; set; }
	}

    /// <summary>
    /// A class which represents the ScrapReason table.
    /// </summary>
	[Table("ScrapReason")]
	public partial class ScrapReason
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual short ScrapReasonID { get; set; }
	    public virtual string Name { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the vStoreWithAddresses view.
    /// </summary>
	[Table("vStoreWithAddresses")]
	public partial class vStoreWithAddress
	{
	    public virtual int BusinessEntityID { get; set; }
	    public virtual string Name { get; set; }
	    public virtual string AddressType { get; set; }
	    public virtual string AddressLine1 { get; set; }
	    public virtual string AddressLine2 { get; set; }
	    public virtual string City { get; set; }
	    public virtual string StateProvinceName { get; set; }
	    public virtual string PostalCode { get; set; }
	    public virtual string CountryRegionName { get; set; }
	}

    /// <summary>
    /// A class which represents the vVendorWithContacts view.
    /// </summary>
	[Table("vVendorWithContacts")]
	public partial class vVendorWithContact
	{
	    public virtual int BusinessEntityID { get; set; }
	    public virtual string Name { get; set; }
	    public virtual string ContactType { get; set; }
	    public virtual string Title { get; set; }
	    public virtual string FirstName { get; set; }
	    public virtual string MiddleName { get; set; }
	    public virtual string LastName { get; set; }
	    public virtual string Suffix { get; set; }
	    public virtual string PhoneNumber { get; set; }
	    public virtual string PhoneNumberType { get; set; }
	    public virtual string EmailAddress { get; set; }
	    public virtual int EmailPromotion { get; set; }
	}

    /// <summary>
    /// A class which represents the Shift table.
    /// </summary>
	[Table("Shift")]
	public partial class Shift
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual byte ShiftID { get; set; }
	    public virtual string Name { get; set; }
	    public virtual DateTime StartTime { get; set; }
	    public virtual DateTime EndTime { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the vVendorWithAddresses view.
    /// </summary>
	[Table("vVendorWithAddresses")]
	public partial class vVendorWithAddress
	{
	    public virtual int BusinessEntityID { get; set; }
	    public virtual string Name { get; set; }
	    public virtual string AddressType { get; set; }
	    public virtual string AddressLine1 { get; set; }
	    public virtual string AddressLine2 { get; set; }
	    public virtual string City { get; set; }
	    public virtual string StateProvinceName { get; set; }
	    public virtual string PostalCode { get; set; }
	    public virtual string CountryRegionName { get; set; }
	}

    /// <summary>
    /// A class which represents the ProductCategory table.
    /// </summary>
	[Table("ProductCategory")]
	public partial class ProductCategory
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int ProductCategoryID { get; set; }
	    public virtual string Name { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ShipMethod table.
    /// </summary>
	[Table("ShipMethod")]
	public partial class ShipMethod
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int ShipMethodID { get; set; }
	    public virtual string Name { get; set; }
	    public virtual decimal ShipBase { get; set; }
	    public virtual decimal ShipRate { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ProductCostHistory table.
    /// </summary>
	[Table("ProductCostHistory")]
	public partial class ProductCostHistory
	{
		[Key]
	    public virtual int ProductID { get; set; }
		[Key]
	    public virtual DateTime StartDate { get; set; }
	    public virtual DateTime? EndDate { get; set; }
	    public virtual decimal StandardCost { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ProductDescription table.
    /// </summary>
	[Table("ProductDescription")]
	public partial class ProductDescription
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int ProductDescriptionID { get; set; }
	    public virtual string Description { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ShoppingCartItem table.
    /// </summary>
	[Table("ShoppingCartItem")]
	public partial class ShoppingCartItem
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int ShoppingCartItemID { get; set; }
	    public virtual string ShoppingCartID { get; set; }
	    public virtual int Quantity { get; set; }
	    public virtual int ProductID { get; set; }
	    public virtual DateTime DateCreated { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ProductDocument table.
    /// </summary>
	[Table("ProductDocument")]
	public partial class ProductDocument
	{
		[Key]
	    public virtual int ProductID { get; set; }
		[Key]
	    public virtual string DocumentNode { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the DatabaseLog table.
    /// </summary>
	[Table("DatabaseLog")]
	public partial class DatabaseLog
	{
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int DatabaseLogID { get; set; }
	    public virtual DateTime PostTime { get; set; }
	    public virtual string DatabaseUser { get; set; }
	    public virtual string Event { get; set; }
	    public virtual string Schema { get; set; }
	    public virtual string Object { get; set; }
	    public virtual string TSQL { get; set; }
	    public virtual string XmlEvent { get; set; }
	}

    /// <summary>
    /// A class which represents the ProductInventory table.
    /// </summary>
	[Table("ProductInventory")]
	public partial class ProductInventory
	{
		[Key]
	    public virtual int ProductID { get; set; }
		[Key]
	    public virtual short LocationID { get; set; }
	    public virtual string Shelf { get; set; }
	    public virtual byte Bin { get; set; }
	    public virtual short Quantity { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the SpecialOffer table.
    /// </summary>
	[Table("SpecialOffer")]
	public partial class SpecialOffer
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int SpecialOfferID { get; set; }
	    public virtual string Description { get; set; }
	    public virtual decimal DiscountPct { get; set; }
	    public virtual string Type { get; set; }
	    public virtual string Category { get; set; }
	    public virtual DateTime StartDate { get; set; }
	    public virtual DateTime EndDate { get; set; }
	    public virtual int MinQty { get; set; }
	    public virtual int? MaxQty { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ErrorLog table.
    /// </summary>
	[Table("ErrorLog")]
	public partial class ErrorLog
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int ErrorLogID { get; set; }
	    public virtual DateTime ErrorTime { get; set; }
	    public virtual string UserName { get; set; }
	    public virtual int ErrorNumber { get; set; }
	    public virtual int? ErrorSeverity { get; set; }
	    public virtual int? ErrorState { get; set; }
	    public virtual string ErrorProcedure { get; set; }
	    public virtual int? ErrorLine { get; set; }
	    public virtual string ErrorMessage { get; set; }
	}

    /// <summary>
    /// A class which represents the ProductListPriceHistory table.
    /// </summary>
	[Table("ProductListPriceHistory")]
	public partial class ProductListPriceHistory
	{
		[Key]
	    public virtual int ProductID { get; set; }
		[Key]
	    public virtual DateTime StartDate { get; set; }
	    public virtual DateTime? EndDate { get; set; }
	    public virtual decimal ListPrice { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Address table.
    /// </summary>
	[Table("Address")]
	public partial class Address
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int AddressID { get; set; }
	    public virtual string AddressLine1 { get; set; }
	    public virtual string AddressLine2 { get; set; }
	    public virtual string City { get; set; }
	    public virtual int StateProvinceID { get; set; }
	    public virtual string PostalCode { get; set; }
	    //public virtual Microsoft.SqlServer.Types.SqlGeography SpatialLocation { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the SpecialOfferProduct table.
    /// </summary>
	[Table("SpecialOfferProduct")]
	public partial class SpecialOfferProduct
	{
		[Key]
	    public virtual int SpecialOfferID { get; set; }
		[Key]
	    public virtual int ProductID { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ProductModel table.
    /// </summary>
	[Table("ProductModel")]
	public partial class ProductModel
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int ProductModelID { get; set; }
	    public virtual string Name { get; set; }
	    public virtual string CatalogDescription { get; set; }
	    public virtual string Instructions { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the AddressType table.
    /// </summary>
	[Table("AddressType")]
	public partial class AddressType
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int AddressTypeID { get; set; }
	    public virtual string Name { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the StateProvince table.
    /// </summary>
	[Table("StateProvince")]
	public partial class StateProvince
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int StateProvinceID { get; set; }
	    public virtual string StateProvinceCode { get; set; }
	    public virtual string CountryRegionCode { get; set; }
	    public virtual bool IsOnlyStateProvinceFlag { get; set; }
	    public virtual string Name { get; set; }
	    public virtual int TerritoryID { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ProductModelIllustration table.
    /// </summary>
	[Table("ProductModelIllustration")]
	public partial class ProductModelIllustration
	{
		[Key]
	    public virtual int ProductModelID { get; set; }
		[Key]
	    public virtual int IllustrationID { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the AWBuildVersion table.
    /// </summary>
	[Table("AWBuildVersion")]
	public partial class AWBuildVersion
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual byte SystemInformationID { get; set; }
	    public virtual string Database_Version { get; set; }
	    public virtual DateTime VersionDate { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ProductModelProductDescriptionCulture table.
    /// </summary>
	[Table("ProductModelProductDescriptionCulture")]
	public partial class ProductModelProductDescriptionCulture
	{
		[Key]
	    public virtual int ProductModelID { get; set; }
		[Key]
	    public virtual int ProductDescriptionID { get; set; }
		[Key]
	    public virtual string CultureID { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the BillOfMaterials table.
    /// </summary>
	[Table("BillOfMaterials")]
	public partial class BillOfMaterial
	{
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int BillOfMaterialsID { get; set; }
		[Key]
	    public virtual int? ProductAssemblyID { get; set; }
		[Key]
	    public virtual int ComponentID { get; set; }
		[Key]
	    public virtual DateTime StartDate { get; set; }
	    public virtual DateTime? EndDate { get; set; }
	    public virtual string UnitMeasureCode { get; set; }
	    public virtual short BOMLevel { get; set; }
	    public virtual decimal PerAssemblyQty { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Store table.
    /// </summary>
	[Table("Store")]
	public partial class Store
	{
		[Key]
	    public virtual int BusinessEntityID { get; set; }
	    public virtual string Name { get; set; }
	    public virtual int? SalesPersonID { get; set; }
	    public virtual string Demographics { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ProductPhoto table.
    /// </summary>
	[Table("ProductPhoto")]
	public partial class ProductPhoto
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int ProductPhotoID { get; set; }
	    public virtual byte[] ThumbNailPhoto { get; set; }
	    public virtual string ThumbnailPhotoFileName { get; set; }
	    public virtual byte[] LargePhoto { get; set; }
	    public virtual string LargePhotoFileName { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ProductProductPhoto table.
    /// </summary>
	[Table("ProductProductPhoto")]
	public partial class ProductProductPhoto
	{
	    public virtual int ProductID { get; set; }
	    public virtual int ProductPhotoID { get; set; }
	    public virtual bool Primary { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the TransactionHistory table.
    /// </summary>
	[Table("TransactionHistory")]
	public partial class TransactionHistory
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int TransactionID { get; set; }
	    public virtual int ProductID { get; set; }
	    public virtual int ReferenceOrderID { get; set; }
	    public virtual int ReferenceOrderLineID { get; set; }
	    public virtual DateTime TransactionDate { get; set; }
	    public virtual string TransactionType { get; set; }
	    public virtual int Quantity { get; set; }
	    public virtual decimal ActualCost { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ProductReview table.
    /// </summary>
	[Table("ProductReview")]
	public partial class ProductReview
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int ProductReviewID { get; set; }
	    public virtual int ProductID { get; set; }
	    public virtual string ReviewerName { get; set; }
	    public virtual DateTime ReviewDate { get; set; }
	    public virtual string EmailAddress { get; set; }
	    public virtual int Rating { get; set; }
	    public virtual string Comments { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the BusinessEntity table.
    /// </summary>
	[Table("BusinessEntity")]
	public partial class BusinessEntity
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int BusinessEntityID { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the TransactionHistoryArchive table.
    /// </summary>
	[Table("TransactionHistoryArchive")]
	public partial class TransactionHistoryArchive
	{
		[Key]
	    public virtual int TransactionID { get; set; }
	    public virtual int ProductID { get; set; }
	    public virtual int ReferenceOrderID { get; set; }
	    public virtual int ReferenceOrderLineID { get; set; }
	    public virtual DateTime TransactionDate { get; set; }
	    public virtual string TransactionType { get; set; }
	    public virtual int Quantity { get; set; }
	    public virtual decimal ActualCost { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ProductSubcategory table.
    /// </summary>
	[Table("ProductSubcategory")]
	public partial class ProductSubcategory
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int ProductSubcategoryID { get; set; }
	    public virtual int ProductCategoryID { get; set; }
	    public virtual string Name { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the BusinessEntityAddress table.
    /// </summary>
	[Table("BusinessEntityAddress")]
	public partial class BusinessEntityAddress
	{
		[Key]
	    public virtual int BusinessEntityID { get; set; }
		[Key]
	    public virtual int AddressID { get; set; }
		[Key]
	    public virtual int AddressTypeID { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ProductVendor table.
    /// </summary>
	[Table("ProductVendor")]
	public partial class ProductVendor
	{
		[Key]
	    public virtual int ProductID { get; set; }
		[Key]
	    public virtual int BusinessEntityID { get; set; }
	    public virtual int AverageLeadTime { get; set; }
	    public virtual decimal StandardPrice { get; set; }
	    public virtual decimal? LastReceiptCost { get; set; }
	    public virtual DateTime? LastReceiptDate { get; set; }
	    public virtual int MinOrderQty { get; set; }
	    public virtual int MaxOrderQty { get; set; }
	    public virtual int? OnOrderQty { get; set; }
	    public virtual string UnitMeasureCode { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the BusinessEntityContact table.
    /// </summary>
	[Table("BusinessEntityContact")]
	public partial class BusinessEntityContact
	{
		[Key]
	    public virtual int BusinessEntityID { get; set; }
		[Key]
	    public virtual int PersonID { get; set; }
		[Key]
	    public virtual int ContactTypeID { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the UnitMeasure table.
    /// </summary>
	[Table("UnitMeasure")]
	public partial class UnitMeasure
	{
		[Key]
	    public virtual string UnitMeasureCode { get; set; }
	    public virtual string Name { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Vendor table.
    /// </summary>
	[Table("Vendor")]
	public partial class Vendor
	{
		[Key]
	    public virtual int BusinessEntityID { get; set; }
	    public virtual string AccountNumber { get; set; }
	    public virtual string Name { get; set; }
	    public virtual byte CreditRating { get; set; }
	    public virtual bool PreferredVendorStatus { get; set; }
	    public virtual bool ActiveFlag { get; set; }
	    public virtual string PurchasingWebServiceURL { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ContactType table.
    /// </summary>
	[Table("ContactType")]
	public partial class ContactType
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int ContactTypeID { get; set; }
	    public virtual string Name { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the CountryRegionCurrency table.
    /// </summary>
	[Table("CountryRegionCurrency")]
	public partial class CountryRegionCurrency
	{
		[Key]
	    public virtual string CountryRegionCode { get; set; }
		[Key]
	    public virtual string CurrencyCode { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the CountryRegion table.
    /// </summary>
	[Table("CountryRegion")]
	public partial class CountryRegion
	{
		[Key]
	    public virtual string CountryRegionCode { get; set; }
	    public virtual string Name { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the WorkOrder table.
    /// </summary>
	[Table("WorkOrder")]
	public partial class WorkOrder
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int WorkOrderID { get; set; }
	    public virtual int ProductID { get; set; }
	    public virtual int OrderQty { get; set; }
		[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
	    public virtual int StockedQty { get; set; }
	    public virtual short ScrappedQty { get; set; }
	    public virtual DateTime StartDate { get; set; }
	    public virtual DateTime? EndDate { get; set; }
	    public virtual DateTime DueDate { get; set; }
	    public virtual short? ScrapReasonID { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the PurchaseOrderDetail table.
    /// </summary>
	[Table("PurchaseOrderDetail", Schema = "Purchasing")]
	public partial class PurchaseOrderDetail
	{
		[Key]
	    public virtual int PurchaseOrderID { get; set; }
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int PurchaseOrderDetailID { get; set; }
	    public virtual DateTime DueDate { get; set; }
	    public virtual short OrderQty { get; set; }
	    public virtual int ProductID { get; set; }
	    public virtual decimal UnitPrice { get; set; }
		[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
	    public virtual decimal LineTotal { get; set; }
	    public virtual decimal ReceivedQty { get; set; }
	    public virtual decimal RejectedQty { get; set; }
		[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
	    public virtual decimal StockedQty { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the CreditCard table.
    /// </summary>
	[Table("CreditCard")]
	public partial class CreditCard
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int CreditCardID { get; set; }
	    public virtual string CardType { get; set; }
	    public virtual string CardNumber { get; set; }
	    public virtual byte ExpMonth { get; set; }
	    public virtual short ExpYear { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Culture table.
    /// </summary>
	[Table("Culture")]
	public partial class Culture
	{
		[Key]
	    public virtual string CultureID { get; set; }
	    public virtual string Name { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the WorkOrderRouting table.
    /// </summary>
	[Table("WorkOrderRouting")]
	public partial class WorkOrderRouting
	{
		[Key]
	    public virtual int WorkOrderID { get; set; }
		[Key]
	    public virtual int ProductID { get; set; }
		[Key]
	    public virtual short OperationSequence { get; set; }
	    public virtual short LocationID { get; set; }
	    public virtual DateTime ScheduledStartDate { get; set; }
	    public virtual DateTime ScheduledEndDate { get; set; }
	    public virtual DateTime? ActualStartDate { get; set; }
	    public virtual DateTime? ActualEndDate { get; set; }
	    public virtual decimal? ActualResourceHrs { get; set; }
	    public virtual decimal PlannedCost { get; set; }
	    public virtual decimal? ActualCost { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Currency table.
    /// </summary>
	[Table("Currency")]
	public partial class Currency
	{
		[Key]
	    public virtual string CurrencyCode { get; set; }
	    public virtual string Name { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the PurchaseOrderHeader table.
    /// </summary>
	[Table("PurchaseOrderHeader")]
	public partial class PurchaseOrderHeader
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int PurchaseOrderID { get; set; }
	    public virtual byte RevisionNumber { get; set; }
	    public virtual byte Status { get; set; }
	    public virtual int EmployeeID { get; set; }
	    public virtual int VendorID { get; set; }
	    public virtual int ShipMethodID { get; set; }
	    public virtual DateTime OrderDate { get; set; }
	    public virtual DateTime? ShipDate { get; set; }
	    public virtual decimal SubTotal { get; set; }
	    public virtual decimal TaxAmt { get; set; }
	    public virtual decimal Freight { get; set; }
		[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
	    public virtual decimal TotalDue { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the CurrencyRate table.
    /// </summary>
	[Table("CurrencyRate")]
	public partial class CurrencyRate
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int CurrencyRateID { get; set; }
	    public virtual DateTime CurrencyRateDate { get; set; }
	    public virtual string FromCurrencyCode { get; set; }
	    public virtual string ToCurrencyCode { get; set; }
	    public virtual decimal AverageRate { get; set; }
	    public virtual decimal EndOfDayRate { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Customer table.
    /// </summary>
	[Table("Customer")]
	public partial class Customer
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int CustomerID { get; set; }
	    public virtual int? PersonID { get; set; }
	    public virtual int? StoreID { get; set; }
	    public virtual int? TerritoryID { get; set; }
		[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
	    public virtual string AccountNumber { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Department table.
    /// </summary>
	[Table("Department")]
	public partial class Department
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual short DepartmentID { get; set; }
	    public virtual string Name { get; set; }
	    public virtual string GroupName { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Document table.
    /// </summary>
	[Table("Document")]
	public partial class Document
	{
		[Key]
	    public virtual string DocumentNode { get; set; }
		[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
	    public virtual short? DocumentLevel { get; set; }
	    public virtual string Title { get; set; }
	    public virtual int Owner { get; set; }
	    public virtual bool FolderFlag { get; set; }
	    public virtual string FileName { get; set; }
	    public virtual string FileExtension { get; set; }
	    public virtual string Revision { get; set; }
	    public virtual int ChangeNumber { get; set; }
	    public virtual byte Status { get; set; }
	    public virtual string DocumentSummary { get; set; }
	    public virtual byte[] _Document { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the SalesOrderDetail table.
    /// </summary>
	[Table("SalesOrderDetail")]
	public partial class SalesOrderDetail
	{
		[Key]
	    public virtual int SalesOrderID { get; set; }
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int SalesOrderDetailID { get; set; }
	    public virtual string CarrierTrackingNumber { get; set; }
	    public virtual short OrderQty { get; set; }
	    public virtual int ProductID { get; set; }
	    public virtual int SpecialOfferID { get; set; }
	    public virtual decimal UnitPrice { get; set; }
	    public virtual decimal UnitPriceDiscount { get; set; }
		[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
	    public virtual decimal LineTotal { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the EmailAddress table.
    /// </summary>
	[Table("EmailAddress")]
	public partial class EmailAddress
	{
		[Key]
	    public virtual int BusinessEntityID { get; set; }
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int EmailAddressID { get; set; }
	    public virtual string _EmailAddress { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Employee table.
    /// </summary>
	[Table("Employee")]
	public partial class Employee
	{
		[Key]
	    public virtual int BusinessEntityID { get; set; }
	    public virtual string NationalIDNumber { get; set; }
	    public virtual string LoginID { get; set; }
	    public virtual string OrganizationNode { get; set; }
		[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
	    public virtual short? OrganizationLevel { get; set; }
	    public virtual string JobTitle { get; set; }
	    public virtual DateTime BirthDate { get; set; }
	    public virtual string MaritalStatus { get; set; }
	    public virtual string Gender { get; set; }
	    public virtual DateTime HireDate { get; set; }
	    public virtual bool SalariedFlag { get; set; }
	    public virtual short VacationHours { get; set; }
	    public virtual short SickLeaveHours { get; set; }
	    public virtual bool CurrentFlag { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the SalesOrderHeader table.
    /// </summary>
	[Table("SalesOrderHeader")]
	public partial class SalesOrderHeader
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int SalesOrderID { get; set; }
	    public virtual byte RevisionNumber { get; set; }
	    public virtual DateTime OrderDate { get; set; }
	    public virtual DateTime DueDate { get; set; }
	    public virtual DateTime? ShipDate { get; set; }
	    public virtual byte Status { get; set; }
	    public virtual bool OnlineOrderFlag { get; set; }
		[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
	    public virtual string SalesOrderNumber { get; set; }
	    public virtual string PurchaseOrderNumber { get; set; }
	    public virtual string AccountNumber { get; set; }
	    public virtual int CustomerID { get; set; }
	    public virtual int? SalesPersonID { get; set; }
	    public virtual int? TerritoryID { get; set; }
	    public virtual int BillToAddressID { get; set; }
	    public virtual int ShipToAddressID { get; set; }
	    public virtual int ShipMethodID { get; set; }
	    public virtual int? CreditCardID { get; set; }
	    public virtual string CreditCardApprovalCode { get; set; }
	    public virtual int? CurrencyRateID { get; set; }
	    public virtual decimal SubTotal { get; set; }
	    public virtual decimal TaxAmt { get; set; }
	    public virtual decimal Freight { get; set; }
		[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
	    public virtual decimal TotalDue { get; set; }
	    public virtual string Comment { get; set; }
	    public virtual Guid rowguid { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

    /// <summary>
    /// A class which represents the EmployeeDepartmentHistory table.
    /// </summary>
	[Table("EmployeeDepartmentHistory")]
	public partial class EmployeeDepartmentHistory
	{
		[Key]
	    public virtual int BusinessEntityID { get; set; }
		[Key]
	    public virtual short DepartmentID { get; set; }
		[Key]
	    public virtual byte ShiftID { get; set; }
		[Key]
	    public virtual DateTime StartDate { get; set; }
	    public virtual DateTime? EndDate { get; set; }
	    public virtual DateTime ModifiedDate { get; set; }
	}

}

