USE [master]
GO

/****** Object:  Database [Destination]    Script Date: 2022/10/16 11:31:40 ******/
CREATE DATABASE [Destination]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Destination', FILENAME = N'/var/opt/mssql/data/Destination.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Destination_log', FILENAME = N'/var/opt/mssql/data/Destination_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Destination].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Destination] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Destination] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Destination] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Destination] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Destination] SET ARITHABORT OFF 
GO

ALTER DATABASE [Destination] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Destination] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Destination] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Destination] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Destination] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Destination] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Destination] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Destination] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Destination] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Destination] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Destination] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Destination] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Destination] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Destination] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Destination] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Destination] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Destination] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Destination] SET RECOVERY FULL 
GO

ALTER DATABASE [Destination] SET  MULTI_USER 
GO

ALTER DATABASE [Destination] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Destination] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Destination] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Destination] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Destination] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Destination] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Destination] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Destination] SET  READ_WRITE 
GO


